version: '3.8'

services:
  pomodoro-pytest:
    build:
      context: .
      target: pomodoro-test  # Build stage to use for pytest
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for testing
    volumes:
      - .:/app  # Mount the current directory to the container for testing
    environment:
      - PYTHONPATH=/app/src:/app
    command: ["poetry", "run", "pytest"]  # For running pytest
    profiles:
      - pytest  # Profile for running pytest

  pomodoro-behave:
    build:
      context: .
      target: pomodoro-test  # Build stage to use for behave
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for testing
    volumes:
      - .:/app  # Mount the current directory to the container for testing
    environment:
      - PYTHONPATH=/app/src:/app
      - AUDIO_OUTPUT=dummy  # Use the dummy audio output for tests as well
    command: ["poetry", "run", "behave"]  # For running behave
    profiles:
      - behave  # Profile for running behave

  pomodoro-pyinstaller:
    build:
      context: .
      target: pyinstaller-binary  # New build stage for PyInstaller
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for PyInstaller
    volumes:
      - .:/app  # Mount the current directory
    profiles:
      - pyinstaller  # Profile for PyInstaller build
    command: ["poetry", "run", "pyinstaller", "--onefile", "--add-data", "resources/logging_config.ini:resources", "--add-data", "resources/sounds/alarm_sound.wav:resources/sounds", "src/pomodoro/pomodoro.py"]
    environment:
      - PYTHONPATH=/app/src:/app
    user: myuser