version: '3.8'

services:
  make-executable:
    build:
      context: .
      target: pomodoro  # Use the build stage defined for pomodoro app
    volumes:
      - .:/app  # Mount the current directory to the container
    environment:
      - PYTHONPATH=/app/src:/app
      - AUDIO_OUTPUT=dummy  # Use the dummy audio output
    entrypoint: ["/bin/bash", "-c"]  # Set entrypoint to allow custom commands
    command: ["poetry build --format wheel && poetry install --no-dev && poetry run pyinstaller --onefile src/pomodoro/pomodoro.py"]
    profiles:
      - make-executable  # Use this profile when needed

  pomodoro-pytest:
    build:
      context: .
      target: pomodoro-test  # Build stage to use for pytest
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for testing
    volumes:
      - .:/app  # Mount the current directory to the container for testing
    environment:
      - PYTHONPATH=/app/src:/app
    command: ["poetry", "run", "pytest"]  # For running pytest

  pomodoro-behave:
    build:
      context: .
      target: pomodoro-test  # Build stage to use for behave
      args:
        MODULE_GROUP: pomodoro  # Use development dependencies for testing
    volumes:
      - .:/app  # Mount the current directory to the container for testing
    environment:
      - PYTHONPATH=/app/src:/app
      - AUDIO_OUTPUT=dummy  # Use the dummy audio output for tests as well
    command: ["poetry", "run", "behave"]  # For running behave
